version: "2"
services:

  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  rabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"

  users:
    build:
      context: users
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        
  dogs:
    build:
      context: dogs
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
  
  tours:
    build:
      context: tours
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  gateway:
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        HTTP.CORS.ENABLED: "true"
        HTTP.CORS.ALLOW-ORIGIN: "http://localhost:4200"
        HTTP.CORS.ALLOW-HEADERS: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        HTTP.CORS.ALLOW-CREDENTIALS: "true"

volumes:
  redis-data: